/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameResult {
  'won' : boolean,
  'betAmount' : bigint,
  'gameType' : GameType,
  'outcome' : string,
  'payout' : bigint,
}
export type GameType = { 'blackjack' : null } |
  { 'diceRoll' : null } |
  { 'coinFlip' : null } |
  { 'roulette' : null };
export interface Promotion {
  'title' : string,
  'bonusAmount' : bigint,
  'description' : string,
}
export type Time = bigint;
export interface Transaction {
  'type' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'joinDate' : Time,
  'totalLost' : bigint,
  'totalWon' : bigint,
  'totalGames' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPromotion' : ActorMethod<[string, string, bigint], undefined>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'getAllPromotions' : ActorMethod<[], Array<Promotion>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordGameResult' : ActorMethod<[GameResult], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'withdraw' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];