/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Promotion = IDL.Record({
  'title' : IDL.Text,
  'bonusAmount' : IDL.Nat,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'joinDate' : Time,
  'totalLost' : IDL.Nat,
  'totalWon' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'type' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Int,
});
export const GameType = IDL.Variant({
  'blackjack' : IDL.Null,
  'diceRoll' : IDL.Null,
  'coinFlip' : IDL.Null,
  'roulette' : IDL.Null,
});
export const GameResult = IDL.Record({
  'won' : IDL.Bool,
  'betAmount' : IDL.Nat,
  'gameType' : GameType,
  'outcome' : IDL.Text,
  'payout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPromotion' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGameResult' : IDL.Func([GameResult], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'withdraw' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Promotion = IDL.Record({
    'title' : IDL.Text,
    'bonusAmount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'joinDate' : Time,
    'totalLost' : IDL.Nat,
    'totalWon' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'type' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Int,
  });
  const GameType = IDL.Variant({
    'blackjack' : IDL.Null,
    'diceRoll' : IDL.Null,
    'coinFlip' : IDL.Null,
    'roulette' : IDL.Null,
  });
  const GameResult = IDL.Record({
    'won' : IDL.Bool,
    'betAmount' : IDL.Nat,
    'gameType' : GameType,
    'outcome' : IDL.Text,
    'payout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPromotion' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGameResult' : IDL.Func([GameResult], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'withdraw' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };